### ISSUE TITLE
Wrong FPC_FULLVERSION value

### ISSUE THREAD

**Issue by zamronypj** [trevoz/lnet#1]
Hi @trevoz

Thank you for your work. However you made error when defines `FPC_FULLVERSION` as `33100` to refer Free Pascal 3.3.1. According to [FPC_FULLVERSION documentation](https://www.freepascal.org/docs-html/prog/progap7.html) value should be `30301` and 3.3.0 should be `30300`.

https://github.com/trevoz/lnet/blob/5bd02ea7d0a1fc0f8043b3cfab1cc3a5579a9f71/lib/lcommon.pp#L462-L470

[See PR 25](https://github.com/almindor/lnet/pull/25)

Fixed in [a6cbbc2320](https://github.com/almindor/lnet/pull/25/commits/a6cbbc2320c5c2987b29e4ab6bf143bf84bc7b0d).

Regards,

**Comment by trevoz** [comment]
Thanks, I'll fix it when I have access to my Mac computers again after I return from interstate. 

Curiously the existing values worked when I compiled the code with the different FPC versions.
