### ISSUE TITLE
Issueds with new version

### ISSUE THREAD

**Issue by han-k59** [trevoz/lnet#2]
Compiling LNET works works but i get issues when I compile my program:

Messages, Warnings: 1
Warning: other sources path of package "lnetbase 0.6.6" contains directory "../lib" which is already in the unit search path.
Compile package lnetvisual 0.6.6: Exit code 1, Errors: 6, Warnings: 1
Verbose: Free Pascal Compiler version 3.3.1-9652-g5bddb3a435 [2021/11/24] for x86_64
Verbose: Copyright (c) 1993-2021 by Florian Klaempfl and others
Warning: The selected debug format is not supported on the current target, not changing the current setting
Verbose: Target OS: Darwin for x86_64
Verbose: Compiling lnetvisual.pas
Verbose: Compiling lclnet.pas
lclnet.pas(45,15) Error: Forward declaration not solved "HandleIgnoreError(TLHandle);"
lclnet.pas(46,15) Error: Forward declaration not solved "HandleIgnoreWrite(TLHandle);"
lclnet.pas(47,15) Error: Forward declaration not solved "HandleIgnoreRead(TLHandle);"
lclnet.pas(48,15) Error: Forward declaration not solved "InternalUnplugHandle(TLHandle);"
lclnet.pas(50,15) Error: Forward declaration not solved "HandleEvents(Int64;LongWord);"
lclnet.pas(58,14) Error: Forward declaration not solved "AddHandle(TLHandle):Boolean;"
lclnet.pas(85,0) Verbose: There were 6 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: /Users/h/Desktop/lazarus_fpcup/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode

Han

**Comment by han-k59** [comment]
In LCLNet.pas the following is missing at around line 82:

 
{$ifdef LCLQT5}
  {$i lclgtkeventer.inc} // identical code ;)
{$endif}

{$ifdef LCLCOCOA}
  {$i lclgtkeventer.inc} // identical code ;)
{$endif}

**Comment by trevoz** [comment]
Are you saying the addition of these IFDEFs fixes the issue?

If so. please specify the exact line number.

(I am currently interstate and do not have access to my Mac computers for the next week.)

**Comment by han-k59** [comment]
Yes this fixed it.

This has to be inserted at line 83.  For each widget there is a line. Currently it contains:

```
implementation

{$ifdef LCLWIN32}
  {$i lclwineventer.inc}
{$endif}

{$ifdef LCLWINCE}
  {$i lclwinceeventer.inc}
{$endif}

{$ifdef LCLGTK}
  {$i lclgtkeventer.inc}
{$endif}

{$ifdef LCLGTK2}
  {$i lclgtkeventer.inc}
{$endif}

{$ifdef LCLQT}
  {$i lclgtkeventer.inc} // identical code ;)
{$endif}

end.   
```

So widgets QT5 and Cocoa (Mac) are missing. I don't understand why these conditions where added. Probably it is easier to remove all widget conditions and replace by a single line as follows:

implementation
 {$i lclgtkeventer.inc} 
end. 

More importantly LNet is not working in my Mac simulator. Identical code works in Windows and Linux but not in the Mac. Maybe there is an other compiler condition where the Mac is excluded. See my other raised Issue.

Han

**Comment by trevoz** [comment]
Thanks. I added the extra widgets rather than collapsing them on the off chance that a new one may be incompatible in future.
