### ISSUE TITLE
LNet doesn't work in macOS

### ISSUE THREAD

**Issue by han-k59** [trevoz/lnet#3]
I have an application which works fine in Windows and Linux. but it doesn't work in the Mac (High Sierra). Any idea why? Attached a small test application which can run as Server(host)  and Client. Two should communicate with each other but it doesn't work for the Mac.

I will drop the same issue at   https://github.com/almindor/lnet

[Archive.zip](https://github.com/trevoz/lnet/files/8550351/Archive.zip)

Thanks in advance, Han

**Comment by trevoz** [comment]
I had a quick look at your projects - it appears that you use the visual components. I do not believe these work with macOS according to the original author. I did not touch them myself as I only use the non-visual LNet library.

**Comment by han-k59** [comment]
Thanks for informing me. If they don't work with the Mac, that would be a pity.

I have decided to switch to Synapse and already made changes. Having TCP functionality in the Mac is a requirement for me.

**Comment by trevoz** [comment]
No worries.
